version: '3.2'

services:

  stt-worker-streaming:
    container_name: stt-standalone-worker-streaming
    build: .
    image: innolab/linto-stt-streaming-cuda:0.0.1
    volumes:
      - ${AM_PATH}:/opt/models/AM
      - ${LM_PATH}:/opt/models/LM
    ports:
      - target: 2700
        published: 2700
    env_file: .env
