version: '3.2'

services:

  stt-worker-streaming:
    container_name: stt-standalone-worker-streaming
    build:
      context: .
      args: 
        PORT: ${PORT}
        GPU_ARCH: ${GPU_ARCH}
    image: innolab/linto-stt-streaming-cuda:0.0.1
    volumes:
      - ${MODEL}:/opt/model/
    ports:
      - target: ${PORT}
        published: ${PORT}
    env_file: .env
